<?php
session_start(); require_once 'config/database.php'; require_once 'config/mail.php'; $db=getDB(); verify_csrf(); $id=(int)($_GET['job_id']??$_POST['job_id']??0);
$q=$db->prepare("SELECT * FROM job_postings WHERE id=? AND status='published'");$q->execute([$id]);$job=$q->fetch();$ok=$err=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  if(!$job)throw new Exception('Job posting is no longer available.');
  $name=trim($_POST['applicant_name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$cover=trim($_POST['cover_letter']??'');
  if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL))throw new Exception('Enter your name and a valid email.');
  if(!isset($_FILES['resume'])||$_FILES['resume']['error']!==UPLOAD_ERR_OK)throw new Exception('Please attach your resume.');
  if($_FILES['resume']['size']>5*1024*1024)throw new Exception('Resume must be 5MB or smaller.');
  $allowed=['pdf'=>'application/pdf','doc'=>'application/msword','docx'=>'application/vnd.openxmlformats-officedocument.wordprocessingml.document'];
  $ext=strtolower(pathinfo($_FILES['resume']['name'],PATHINFO_EXTENSION)); if(!isset($allowed[$ext]))throw new Exception('Resume must be PDF, DOC, or DOCX.');
  $dir=__DIR__.'/uploads/resumes';if(!is_dir($dir))mkdir($dir,0755,true);$file=bin2hex(random_bytes(16)).'.'.$ext;$target=$dir.'/'.$file;
  if(!move_uploaded_file($_FILES['resume']['tmp_name'],$target))throw new Exception('Unable to save resume.');
  $path='uploads/resumes/'.$file;$db->prepare("INSERT INTO job_applications(job_id,applicant_name,email,phone,cover_letter,resume_path) VALUES(?,?,?,?,?,?)")->execute([$id,$name,$email,$phone,$cover,$path]);
  @send_hr_email($email,'Application received for '.$job['title'],'<h2>Application received</h2><p>Thank you, '.h($name).'. Your application for <strong>'.h($job['title']).'</strong> has been received.</p>');
  $ok='Application submitted successfully.';
 }catch(Throwable $e){$err=$e->getMessage();}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Apply - <?php echo h($job['title']??'Job'); ?></title><link rel="stylesheet" href="assets/vendor/bootstrap/bootstrap.min.css"><link rel="stylesheet" href="assets/vendor/fontawesome/all.min.css"><link rel="stylesheet" href="assets/css/custom.css"></head><body><main class="container py-5" style="max-width:850px"><a href="login.php" class="btn btn-link mb-3"><i class="fas fa-arrow-left"></i> Back</a><?php if($ok):?><div class="alert alert-success"><i class="fas fa-check-circle me-2"></i><?php echo h($ok);?></div><?php elseif($err):?><div class="alert alert-danger"><?php echo h($err);?></div><?php endif;?><?php if($job):?><div class="card border-0 shadow-sm"><div class="card-body p-4"><span class="badge bg-primary"><?php echo h($job['employment_type']);?></span><h2 class="mt-3"><?php echo h($job['title']);?></h2><p class="text-muted"><?php echo h($job['department']);?> · <?php echo h($job['location']);?></p><hr><p><?php echo nl2br(h($job['description']));?></p><h6>Requirements</h6><p><?php echo nl2br(h($job['requirements']));?></p><form method="post" enctype="multipart/form-data" class="mt-4"><?php echo csrf_field();?><input type="hidden" name="job_id" value="<?php echo $id;?>"><div class="row g-3"><div class="col-md-6"><label class="form-label">Full Name</label><input name="applicant_name" class="form-control" required></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" name="email" class="form-control" required></div><div class="col-md-6"><label class="form-label">Phone</label><input name="phone" class="form-control"></div><div class="col-12"><label class="form-label">Cover Letter</label><textarea name="cover_letter" class="form-control" rows="5"></textarea></div><div class="col-12"><label class="form-label">Resume (PDF/DOC/DOCX, max 5MB)</label><input type="file" name="resume" class="form-control" accept=".pdf,.doc,.docx" required></div></div><button class="btn btn-primary mt-4"><i class="fas fa-paper-plane me-1"></i> Submit Application</button></form></div></div><?php else:?><div class="alert alert-warning">Job posting not found.</div><?php endif;?></main><script src="assets/vendor/bootstrap/bootstrap.bundle.min.js"></script></body></html>